name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core:    ^2.24.0
  firebase_auth:    ^4.18.1
  cloud_firestore:  ^4.16.1

  # State management
  provider:         ^6.1.1

  # Charts
  fl_chart:         ^0.66.0

  # Local storage
  shared_preferences: ^2.2.3

  # Connectivity (for “No internet” handling)
  connectivity_plus:  ^6.0.5

  # Date formatting (optional, but often handy for timestamps)
  intl:             ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  
